const WORD_BANK = {
    "Outer Space": {
        words: [
            { word: "ASTEROID", hint: "Rocky body orbiting the sun" },
            { word: "NEBULA", hint: "Cloud of gas and dust in space" },
            { word: "GALAXY", hint: "System of millions of stars" },
            { word: "ECLIPSE", hint: "When one celestial body blocks another" },
            { word: "SATELLITE", hint: "Object orbiting a planet" },
            { word: "COSMOS", hint: "The universe as a whole" },
            { word: "METEOR", hint: "Shooting star" },
            { word: "GRAVITY", hint: "Force that pulls objects together" },
            { word: "SUPERNOVA", hint: "Explosive death of a star" },
            { word: "DARK MATTER", hint: "Invisible substance in space" },
            { word: "BLACK HOLE", hint: "Nothing can escape its pull" },
            { word: "MILKY WAY", hint: "Our home galaxy" },
            { word: "CONSTELLATION", hint: "Pattern of stars in the sky" },
            { word: "LUNAR", hint: "Related to the moon" },
            { word: "ORBIT", hint: "Path around a celestial body" },
            { word: "PLUTO", hint: "Dwarf planet, once the ninth" },
            { word: "COMET", hint: "Icy body with a glowing tail" },
            { word: "SATURN", hint: "Planet with magnificent rings" },
            { word: "JUPITER", hint: "Largest planet in our system" },
            { word: "MERCURY", hint: "Closest planet to the sun" }
        ],
        emoji: "🚀"
    },
    "Animals": {
        words: [
            { word: "ELEPHANT", hint: "Largest land animal" },
            { word: "PENGUIN", hint: "Tuxedo-wearing bird that can't fly" },
            { word: "CHAMELEON", hint: "Lizard that changes color" },
            { word: "DOLPHIN", hint: "Intelligent ocean mammal" },
            { word: "GIRAFFE", hint: "Tallest living animal" },
            { word: "OCTOPUS", hint: "Eight-armed sea creature" },
            { word: "PLATYPUS", hint: "Egg-laying mammal with a bill" },
            { word: "FLAMINGO", hint: "Pink bird that stands on one leg" },
            { word: "CHEETAH", hint: "Fastest land animal" },
            { word: "PANGOLIN", hint: "Scaly anteater" },
            { word: "NARWHAL", hint: "Unicorn of the sea" },
            { word: "IGUANA", hint: "Large tropical lizard" },
            { word: "WOLVERINE", hint: "Fierce small bear-like mammal" },
            { word: "ARMADILLO", hint: "Armored rolling mammal" },
            { word: "BARRACUDA", hint: "Fast predatory fish" },
            { word: "TOUCAN", hint: "Bird with a colorful oversized bill" },
            { word: "MONGOOSE", hint: "Snake-fighting mammal" },
            { word: "ANACONDA", hint: "Massive South American snake" },
            { word: "JELLYFISH", hint: "Translucent stinging sea creature" },
            { word: "ALBATROSS", hint: "Seabird with the largest wingspan" }
        ],
        emoji: "🦁"
    },
    "Movies": {
        words: [
            { word: "INCEPTION", hint: "Dreams within dreams" },
            { word: "GLADIATOR", hint: "Roman arena fighter" },
            { word: "TITANIC", hint: "Unsinkable ship love story" },
            { word: "AVATAR", hint: "Blue aliens on Pandora" },
            { word: "JAWS", hint: "Shark terrorizes a beach town" },
            { word: "ROCKY", hint: "Underdog boxer from Philadelphia" },
            { word: "PSYCHO", hint: "Hitchcock's shower scene classic" },
            { word: "FROZEN", hint: "Let it go!" },
            { word: "MATRIX", hint: "Red pill or blue pill" },
            { word: "ALIENS", hint: "In space, no one can hear you scream" },
            { word: "JUMANJI", hint: "Dangerous board game comes alive" },
            { word: "BAMBI", hint: "Young deer in the forest" },
            { word: "COCO", hint: "Boy visits the Land of the Dead" },
            { word: "DUNKIRK", hint: "WWII beach evacuation" },
            { word: "ZODIAC", hint: "Hunt for a serial killer" },
            { word: "BRAVE", hint: "Scottish princess and archery" },
            { word: "ARRIVAL", hint: "Linguist decodes alien language" },
            { word: "WHIPLASH", hint: "Intense drumming and a tough teacher" },
            { word: "SPOTLIGHT", hint: "Journalists uncover church scandal" },
            { word: "PARASITE", hint: "Rich and poor families collide" }
        ],
        emoji: "🎬"
    },
    "Food": {
        words: [
            { word: "CROISSANT", hint: "Flaky French pastry" },
            { word: "SPAGHETTI", hint: "Long thin Italian pasta" },
            { word: "AVOCADO", hint: "Green fruit loved on toast" },
            { word: "CHOCOLATE", hint: "Sweet treat from cacao beans" },
            { word: "BRUSCHETTA", hint: "Italian toasted bread appetizer" },
            { word: "DUMPLING", hint: "Filled dough pocket" },
            { word: "PANCAKE", hint: "Flat breakfast cake on a griddle" },
            { word: "JALAPENO", hint: "Spicy green pepper" },
            { word: "TIRAMISU", hint: "Italian coffee-flavored dessert" },
            { word: "SOURDOUGH", hint: "Bread made with fermented starter" },
            { word: "CINNAMON", hint: "Warm spice from tree bark" },
            { word: "MOZZARELLA", hint: "Stretchy white cheese" },
            { word: "RISOTTO", hint: "Creamy Italian rice dish" },
            { word: "WASABI", hint: "Spicy green Japanese condiment" },
            { word: "PRETZEL", hint: "Twisted salted bread snack" },
            { word: "QUINOA", hint: "Protein-rich ancient grain" },
            { word: "MACARON", hint: "Colorful French sandwich cookie" },
            { word: "BURRITO", hint: "Wrapped Mexican tortilla meal" },
            { word: "KOMBUCHA", hint: "Fermented fizzy tea drink" },
            { word: "FOCACCIA", hint: "Flat Italian herb bread" }
        ],
        emoji: "🍕"
    },
    "Technology": {
        words: [
            { word: "ALGORITHM", hint: "Step-by-step problem solving process" },
            { word: "BLUETOOTH", hint: "Wireless short-range connection" },
            { word: "FIREWALL", hint: "Network security barrier" },
            { word: "QUANTUM", hint: "Computing at the subatomic level" },
            { word: "PIXEL", hint: "Smallest unit of a digital image" },
            { word: "ENCRYPT", hint: "Scramble data for security" },
            { word: "BROWSER", hint: "Software for viewing websites" },
            { word: "STREAMING", hint: "Watching media in real time" },
            { word: "MALWARE", hint: "Malicious software" },
            { word: "BANDWIDTH", hint: "Data transfer capacity" },
            { word: "FIRMWARE", hint: "Software built into hardware" },
            { word: "ROBOTICS", hint: "Science of building machines" },
            { word: "DATABASE", hint: "Organized collection of data" },
            { word: "ETHERNET", hint: "Wired network technology" },
            { word: "GIGABYTE", hint: "About a billion bytes" },
            { word: "COMPILER", hint: "Translates code to machine language" },
            { word: "PHISHING", hint: "Scam to steal your info" },
            { word: "SILICON", hint: "Element chips are made from" },
            { word: "BINARY", hint: "Ones and zeros" },
            { word: "KERNEL", hint: "Core of an operating system" }
        ],
        emoji: "💻"
    },
    "Geography": {
        words: [
            { word: "AMAZON", hint: "Largest rainforest and river" },
            { word: "SAHARA", hint: "Largest hot desert" },
            { word: "EVEREST", hint: "Tallest mountain on Earth" },
            { word: "ICELAND", hint: "Land of fire and ice" },
            { word: "TSUNAMI", hint: "Giant ocean wave" },
            { word: "VOLCANO", hint: "Mountain that erupts" },
            { word: "GLACIER", hint: "Slow-moving river of ice" },
            { word: "BERMUDA", hint: "Triangle of mysterious disappearances" },
            { word: "FJORD", hint: "Narrow sea inlet between cliffs" },
            { word: "TUNDRA", hint: "Cold treeless Arctic plain" },
            { word: "CANYON", hint: "Deep valley carved by a river" },
            { word: "ARCHIPELAGO", hint: "Chain of islands" },
            { word: "PLATEAU", hint: "Flat elevated landform" },
            { word: "PENINSULA", hint: "Land surrounded by water on three sides" },
            { word: "EQUATOR", hint: "Imaginary line dividing Earth in half" },
            { word: "MONSOON", hint: "Seasonal heavy rain pattern" },
            { word: "OASIS", hint: "Fertile spot in a desert" },
            { word: "PRAIRIE", hint: "Wide open grassland" },
            { word: "ATOLL", hint: "Ring-shaped coral island" },
            { word: "DELTA", hint: "Where a river meets the sea" }
        ],
        emoji: "🌍"
    }
};
